### ISSUE TITLE
What doest that mean ? inOrder = inOrder();

### ISSUE THREAD

**Issue by sahilk335** [pramodbhadana/letsdosomething#2]
https://github.com/pramodbhadana/letsdosomething/blob/918e607874b711c40f2c2f25a4c98d23636200d2/src/tree/BinarySearchTree.java#L169

**Comment by pramodbhadana** [comment]
Well, the class BinarySearchTree is extending the Tree class and inOrder is a method of Tree class which returns an arraylist containing the inOrder Traversal of the Tree.
